apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.app.name }}"
  labels:
    {{- include "chart.labels" . | nindent 6 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: {{ .Values.app.port_name }}
  selector:
    app.kubernetes.io/instance: firsthelmapp
    app.kubernetes.io/name: backend-msa
